adpp_args:
  n_actions: 5
data_args:
  alpha: 0.5
  grid_world_args:
    atol: 0.2
    gamma: 0.99
    seed: ${seed}
  include_goal: false
  mask_nonactions: true
  n_data: 100_000
  n_episodes: 1
  steps_per_context: ${model_args.steps_per_context}
  value_iteration_args:
    n_policies: ${data_args.n_data}
  yield_every: 1
data_path: data/ad
evaluate_args:
  dummy_vec_env: false
  gamma: ${data_args.grid_world_args.gamma}
  n_rollouts: 10
grad_norm_clip: 1.0
load_path: null
log_interval: 20
log_tables_interval: 5
lr: 0.001
metrics_args: {}
model_args:
  embd_pdrop: 0.1
  layer_args:
    causal_self_attention_args:
      attn_pdrop: 0.1
      n_head: 4
    resid_pdrop: 0.1
  n_embd: 32
  n_layer: 4
  steps_per_context: 50
n_batch: 50
n_epochs: 2
optimizer_config:
  betas: [0.9, 0.95]
  weight_decay: 0.1
save_interval: 400
seed: 0
test_ad_interval: 5
test_adpp_interval: null
weights_args:
  actions: 5
