data_args:
  grid_size: 3
  grid_world_args:
    atol: 0.2
    gamma: 0.99
  include_goal: true
  mask_nonactions: true
  n_data: 100_000
  n_episodes: 1
  optimal_policy: false
  steps_per_context: ${model_args.steps_per_context}
  value_iteration_args:
    n_policies: ${data_args.n_data}
evaluate_args:
  gamma: ${data_args.grid_world_args.gamma}
  n_rollouts: 10
grad_norm_clip: 1.0
log_freq: 20
lr: 0.001
metrics_args:
  steps_per_graph: 1
model_args:
  embd_pdrop: 0.1
  layer_args:
    causal_self_attention_args:
      attn_pdrop: 0.1
      n_head: 4
    resid_pdrop: 0.1
  n_embd: 32
  n_layer: 4
  steps_per_context: 50
n_batch: 50
n_epochs: 2
optimizer_config:
  betas: [0.9, 0.95]
  weight_decay: 0.1
run_name: trial
save_freq: 400
seed: 0
test_freq: 100
weights_args:
  actions: 5
  rewards: 1
  # values: 1
