data_args:
  dense_reward: true
  grid_size: 2
  grid_world_args:
    absorbing_state: false
    terminate_on_goal: false
  include_goal: false
  n_data: 3
  yield_every: null
data_path: grid_world/explore_then_exploit
log_tables_interval: 20
model_args:
  embd_pdrop: 0.0
  layer_args:
    causal_self_attention_args:
      attn_pdrop: 0.0
      n_head: 2
    resid_pdrop: 0.0
  n_embd: 32
  n_layer: 1
  steps_per_context: 100
n_epochs: 100000
save_interval: 400000
test_ad_interval: 25000
