data_args:
  dense_reward: true
  grid_size: 2
  grid_world_args:
    absorbing_state: false
    terminate_on_goal: false
  include_goal: false
  n_data: 2
  yield_every: null
data_path: grid_world/explore_then_exploit
log_tables_interval: 20
n_epochs: 100000
save_interval: 400000
test_ad_interval: 25000
